--:setvar DATABASE_NAME "MyDbname"
--:setvar DATABASE_PATH_PRIMARY "C:\Program Files\Database Setup\"
--:setvar DATABASE_PATH_LOG "C:\Program Files\Database Setup\"

GO

Print 'START 0.CreateDatabase.sql will Drop and recreate the DB'
 
GO

IF EXISTS (SELECT name FROM master.dbo.sysdatabases WHERE name = N'$(DATABASE_NAME)')
ALTER DATABASE [$(DATABASE_NAME)] SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
IF EXISTS (SELECT name FROM master.dbo.sysdatabases WHERE name = N'$(DATABASE_NAME)')
DROP DATABASE [$(DATABASE_NAME)]
GO

CREATE DATABASE [$(DATABASE_NAME)]
 ON  PRIMARY 
( NAME = N'$(DATABASE_NAME)', FILENAME = N'$(DATABASE_PATH_PRIMARY)\$(DATABASE_NAME)_Data.MDF' , SIZE = 5120KB , FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'$(DATABASE_NAME)_log', FILENAME = N'$(DATABASE_PATH_LOG)\$(DATABASE_NAME)_Log.LDF' , SIZE = 1024KB , FILEGROWTH = 10%)

--ALTER DATABASE [$(DATABASE_NAME)] SET COMPATIBILITY_LEVEL = 90
GO
ALTER DATABASE [$(DATABASE_NAME)] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [$(DATABASE_NAME)] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [$(DATABASE_NAME)] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [$(DATABASE_NAME)] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [$(DATABASE_NAME)] SET ARITHABORT OFF 
GO
ALTER DATABASE [$(DATABASE_NAME)] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [$(DATABASE_NAME)] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [$(DATABASE_NAME)] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [$(DATABASE_NAME)] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [$(DATABASE_NAME)] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [$(DATABASE_NAME)] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [$(DATABASE_NAME)] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [$(DATABASE_NAME)] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [$(DATABASE_NAME)] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [$(DATABASE_NAME)] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [$(DATABASE_NAME)] SET  DISABLE_BROKER 
GO
ALTER DATABASE [$(DATABASE_NAME)] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [$(DATABASE_NAME)] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [$(DATABASE_NAME)] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [$(DATABASE_NAME)] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [$(DATABASE_NAME)] SET  READ_WRITE 
GO
ALTER DATABASE [$(DATABASE_NAME)] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [$(DATABASE_NAME)] SET  MULTI_USER 
GO
ALTER DATABASE [$(DATABASE_NAME)] SET PAGE_VERIFY CHECKSUM  
GO
--ALTER DATABASE [$(DATABASE_NAME)] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
USE [$(DATABASE_NAME)]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [$(DATABASE_NAME)] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
ALTER DATABASE [$(DATABASE_NAME)] SET MULTI_USER

GO

USE  [$(DATABASE_NAME)]

GO

--DEV SERVER
IF @@SERVERNAME = 'Server\Instance'
 BEGIN
		--Adds a user to the current database.
		CREATE USER [domainUserName] FOR LOGIN [loginName] WITH DEFAULT_SCHEMA=[dbo] 
		
		PRINT 'Created User domainUserName For Login'
END	 

 
GO

Print 'END 0.CreateDatabase.sql'
 
GO