@ECHO off

REM In this batch file is a% WIX% environment variable generated by the WiX installer. 
REM Check if you need to replace the paths to the database solution paths created with SQL Server Management Studio or the location where your SQL Scripts are stored.
REM Check if you need to replace the path to the WIX tools.

REM *************************************************************************************************
REM Double clicking on the batch file creates two files: 
REM		Components_Project.wxs and 
REM		Components_Dir.wxs
REM
REM  Use the contents of the files to update the Product.wxs 
REM *************************************************************************************************

REM http://wix.sourceforge.net/manual-wix3/heat.htm


"%WIX%bin\heat.exe" dir "C:\Development\GitHub\WixDatabaseInstaller\SQLScripts" -cg CG_General -out Components_Dir.wxs -dr INSTALLLOCATION -gg -var var.SourceItemsDir -template product

"%WIX%bin\heat.exe" project "C:\Development\GitHub\WixDatabaseInstaller\Database.CustomAction\Database.CustomAction.csproj" -pog Binaries -pog Documents -pog Satellites -cg CG_General -out Components_Project.wxs -dr INSTALLLOCATION -gg -var var.SourceItemsDir -template product

PAUSE
@ECHO on
